# Solr 4.x required for silverstripe
FROM makuk66/docker-solr:4.10.4

MAINTAINER Mohamed Alsharaf <mohamed.alsharaf@gmail.com>

# Change as needed to set max and min memory
ENV SOLR_HEAP=512m

# To be able to access index folder
USER root
