version: "2"

services:
  site:
      build: ./nginx/
      ports:
        - "${VIRTUAL_PORT}:80"
      links:
          - php
      external_links:
          - proxy:dockergen
      volumes_from:
          - app
      volumes:
          - ./nginx/logs:/var/log/nginx
      environment:
          - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
      env_file:
          - ./env/web.env
          - ./env/db.env

  mysql:
      build: ./db/
      volumes_from:
          - data
      env_file:
          - ./env/db.env

  php:
      build: ./php/
      expose:
          - 9000
      links:
          - mysql
      volumes_from:
          - app
      env_file:
          - ./env/db.env
          - ./env/web.env

  composer:
      build: ./composer/
      volumes:
          - ~/.composer:/composer
          - ~/.ssh:/root/.ssh
          - ~/.netrc:/root/.netrc
      volumes_from:
          - app

  app:
      image: php:5.6-fpm
      volumes:
          - ./site:/var/www/html
          - ./php/mail:/var/www/mail
      command: "true"
      tty: true

  data:
      image: mariadb:10.1
      volumes:
          - /var/lib/mysql
      command: "true"
