version: "3"

services:
  site:
    container_name: ${APP_NAME}_site_1
    build: ./nginx/
    image: mo_nginx
    ports:
      - "${VIRTUAL_PORT}:80"
    links:
      - php
    external_links:
      - proxy:dockergen
    volumes:
      - app-sync:/var/www/html:nocopy
      - ./nginx/logs:/var/log/nginx
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    env_file:
      - ./env/web.env
      - ./env/db.env

  mysql:
    container_name: ${APP_NAME}_mysql_1
    build: ./db/
    image: mo_db
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/database:/var/lib/mysql:consistent
    env_file:
      - ./env/web.env
      - ./env/db.env

  composer:
    container_name: ${APP_NAME}_composer_1
    image: mo_composer
    build: ./composer/
    volumes:
      - app-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/composer:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached

  php:
    container_name: ${APP_NAME}_php_1
    build: ./php/
    image: mo_php
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - app-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/composer:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached
      - ./php/mail:/var/www/mail
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    env_file:
      - ./env/db.env
      - ./env/web.env
    tty: true

volumes:
  app-sync:
    external:
      name: "${APP_NAME}_dockersync_1"
