version: "2"
options:
  verbose: true
  cli_mode: 'thor'
syncs:
    {{volume-name}}:
      src: '{{root_path}}/site/'
      notify_terminal: true
      monit_enable: true
      monit_interval: 10
      monit_high_cpu_cycles: 6
      watch_args: '-v'
      sync_userid: '33'
      sync_args: "-ignore='Path .idea' -ignore='Path .git' -ignore='Name .DS_Store' -ignore='Path .docker-sync' -ignore='BelowPath node_modules' -ignore='Path vendor/*'"
