version: "2"
options:
  verbose: true
  compose-dev-file-path: '{{root_path}}/docker-compose-dev.yml'
  cli_mode: 'thor'
syncs:
  {{volume-name}}:
    src: '{{root_path}}/site/'
    watch_in_container: true
    notify_terminal: true
    watch_strategy: 'fswatch'
    sync_excludes: ['.git', '.gitignore', 'node_modules', '.bower_components', 'sass-cache', '.sass-cache',  '.editorconfig', 'bitbucket-pipelines.yml', '*.scss', '*.sass']
    watch_excludes: ['.git', '.gitignore', 'node_modules', '.bower_components', 'sass-cache', '.sass-cache',  '.editorconfig', 'bitbucket-pipelines.yml', '*.scss', '*.sass']
    monit_enable: true
    monit_interval: 10
    monit_high_cpu_cycles: 6
    watch_args: '-v'
    sync_userid: '33'
