#!/bin/bash

export DOCKER_MACHINE_IP=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'  | grep -m1 "") &&
export $(grep "^[^#]" env/web.env | xargs) &&

PARAM=${1:-up -d}
DOCKER_VOLUME="{{volume-name}}"
TYPE=${1:-up -d}

if [ "$TYPE" = "up -d" ]
then
   docker-compose -f docker-compose-dev.yml up -d
elif [ "$TYPE" = "stop" ]
then
   docker-compose -f docker-compose-dev.yml stop
else
  docker-compose -f docker-compose-dev.yml ${1:-up -d}
fi
