version: "2"

services:

  proxy:
      build: ./proxy/
      container_name: 'nginx_proxy'
      ports:
          - '80:80'
      volumes:
        - "./proxy/conf.d:/etc/nginx/conf.d"
        - "./proxy/vhost.d:/etc/nginx/vhost.d"
        - "./proxy/certs:/etc/nginx/certs:ro"
        - "./proxy/logs:/var/log/nginx/"
        - "/usr/share/nginx/html"

  dockergen:
      image: jwilder/docker-gen
      container_name: docker_gen
      volumes:
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "./proxy/templates:/etc/docker-gen/templates:ro"
      volumes_from:
        - proxy
      entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx_proxy -watch -only-exposed -wait 5s:30s -notify "/etc/init.d/nginx reload"  /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
