#!/bin/bash

if [ -d /var/www/html/public/assets ]; then chown -R www-data:www-data /var/www/html/public/assets; fi
if [ -d /var/www/html/assets ]; then chown -R www-data:www-data /var/www/html/assets; fi

# Solr directory
chown -R www-data:www-data /var/www/solr
