version: "3"

services:
  site:
    container_name: {{name}}_site_1
    build: ./apache/
    image: mo_apache
    ports:
      - "${VIRTUAL_PORT}:80"
    links:
      - php
    external_links:
      - proxy:dockergen
    volumes:
      - {{volume-name}}:/var/www/html:nocopy
      - ./apache/logs:/var/log/apache2
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    env_file:
      - ./env/web.env
      - ./env/db.env

  mysql:
    container_name: {{name}}_mysql_1
    build: ./db/
    image: mo_db
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/database:/var/lib/mysql:consistent
    env_file:
      - ./env/web.env
      - ./env/db.env

  composer:
    container_name: {{name}}_composer_1
    image: mo_composer
    build: ./composer/
    volumes:
      - {{volume-name}}:/var/www/html:nocopy
      - ~/.composer:/var/www/composer:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached

  php:
    container_name: {{name}}_php_1
    build: ./php/
    image: mo_php
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - {{volume-name}}:/var/www/html:nocopy
      - ~/.composer:/var/www/composer:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached
      - ./php/mail:/var/www/mail
      - ../solr/myindex:/var/www/solr:consistent
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    env_file:
      - ./env/db.env
      - ./env/ss.env
      - ./env/web.env
    tty: true

  solr:
    container_name: {{name}}_solr_1
    image: mo_solr
    build: ./solr/
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - ./solr/myindex:/var/www/solr:consistent

volumes:
    {{volume-name}}:
      external: true
