version: "3"

services:
  site:
    container_name: ${APP_NAME}_site_1
    build: ./apache/
    image: mo_apache
    ports:
      - "${VIRTUAL_PORT}:80"
    links:
      - php
    external_links:
      - proxy:dockergen
    volumes:
      - app-sync:/var/www/html:nocopy
      - ./apache/logs:/var/log/apache2
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    env_file:
      - ./env/web.env
      - ./env/db.env

  mysql:
    container_name: ${APP_NAME}_mysql_1
    build: ./db/
    image: mo_db
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/database:/var/lib/mysql:consistent
    env_file:
      - ./env/web.env
      - ./env/db.env

  composer:
    container_name: ${APP_NAME}_composer_1
    image: mo_composer
    build: ./composer/
    volumes:
      - app-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/composer:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached

  php:
    container_name: ${APP_NAME}_php_1
    build: ./php/
    image: mo_php
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - app-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/composer:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached
      - ./php/mail:/var/www/mail
      - solr-data:/var/www/solr
    environment:
      - "DOCKER_MACHINE_IP=${DOCKER_MACHINE_IP}"
    env_file:
      - ./env/db.env
      - ./env/web.env
    tty: true

  solr:
    container_name: ${APP_NAME}_solr_1
    image: mo_solr
    build: ./solr/
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - solr-data:/var/www/solr

  front:
    container_name: ${APP_NAME}_front_1
    image: mo_front
    build: ./front/
    working_dir: /var/www/html/${THEME_DIR}
    volumes:
      - app-sync:/var/www/html:nocopy
      - ~/.ssh:/root/.ssh:cached
      - ~/.netrc:/root/.netrc:cached
    env_file:
      - ./env/web.env

volumes:
  app-sync:
    external:
      name: "${APP_NAME}_dockersync_1"
  solr-data:
