version: "2"
options:
  verbose: true
  cli_mode: 'thor'
syncs:
  {{volume-name}}:
    src: '{{root_path}}/site/'
    notify_terminal: true
    sync_excludes: ['.git', '.idea/', '.gitignore', 'node_modules', '.bower_components', 'sass-cache', '.sass-cache', './vendor/', '.editorconfig', 'bitbucket-pipelines.yml']
    watch_excludes: ['.git', '.idea/', '.gitignore', 'node_modules', '.bower_components', 'sass-cache', '.sass-cache', './vendor/', '.editorconfig', 'bitbucket-pipelines.yml']
    monit_enable: true
    monit_interval: 10
    monit_high_cpu_cycles: 6
    watch_args: '-v'
    sync_userid: '33'
    sync_args:
      - "-ignore='Path .idea'"          # no need to send PHPStorm config to container
      - "-ignore='Path .git'"           # ignore the main .git repo
      - "-ignore='BelowPath .git'"      # also ignore .git repos in subfolders such as in composer vendor dirs
      - "-ignore='BelowPath node_modules'" # remove this if you need code completion
      # - "-ignore='Path vendor/*'"     # we could ignore the composer vendor folder, but then you won't have code completion in your IDE
