#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

export DOCKER_MACHINE_IP=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'  | grep -m1 "") &&
export $(grep "^[^#]" env/web.env | xargs) &&

PARAM=${1:-up -d}
DOCKER_VOLUME="{{volume-name}}"
TYPE=${1:-up -d}

if [ "$TYPE" = "up -d" ]
then
   docker-sync start && docker-compose up -d
elif [ "$TYPE" = "stop" ]
then
   docker-sync stop && docker-compose down
else
   docker-compose ${1:-up -d}
fi
