#!/bin/bash

export DOCKER_MACHINE_IP=$(docker-machine ip default) &&
export $(grep "^[^#]" env/web.env | xargs) &&

PARAM=${1:-up -d}
DOCKER_VOLUME="{{volume-name}}"
TYPE=${1:-up -d}

if [ "$TYPE" = "up -d" ]
then
   docker-compose -f docker-compose-dev.yml up -d
elif [ "$TYPE" = "stop" ]
then
   docker-compose -f docker-compose-dev.yml stop
else
  docker-compose -f docker-compose-dev.yml ${1:-up -d}
fi
